### ISSUE TITLE
build error via termux in android device

### ISSUE THREAD

**Issue by conrong** [Bigfoot71/Raymob#11]
hello, what caused this error. Try to build in android device via termux.

:app:checkDebugDuplicateClasses

> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: /data/data/com.termux/files/home/opt/android-sdk/cmake/3.22.1/bin/cmake[1]: syntax error: unexpected ')'

> Task :app:processDebugManifestForPackage
> Task :app:mergeDebugJavaResource

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using /data/data/com.termux/files/home/Raymob-master/app/src/main/cpp/CMakeLists.txt: C++ build system [configure] failed while executing:
      /data/data/com.termux/files/home/opt/android-sdk/cmake/3.22.1/bin/cmake \
        -H/data/data/com.termux/files/home/Raymob-master/app/src/main/cpp \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=24 \
        -DANDROID_PLATFORM=android-24 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/data/data/com.termux/files/home/opt/android-sdk/ndk/25.1.8937393 \
        -DCMAKE_ANDROID_NDK=/data/data/com.termux/files/home/opt/android-sdk/ndk/25.1.8937393 \
        -DCMAKE_TOOLCHAIN_FILE=/data/data/com.termux/files/home/opt/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/data/data/com.termux/files/home/opt/android-sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/Raymob-master/app/build/intermediates/cxx/Debug/4n1p4t41/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/data/data/com.termux/files/home/Raymob-master/app/build/intermediates/cxx/Debug/4n1p4t41/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/data/data/com.termux/files/home/Raymob-master/app/.cxx/Debug/4n1p4t41/arm64-v8a \
        -GNinja \
        -DAPP_LIB_NAME=raymob
    from /data/data/com.termux/files/home/Raymob-master/app
  /data/data/com.termux/files/home/opt/android-sdk/cmake/3.22.1/bin/cmake[1]: syntax error: unexpected ')'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by Bigfoot71** [comment]
Hello, someone on the raylib Discord had encountered a very similar error to yours while trying to compile via Termux on Android. It turned out that the issue was related to their Termux setup. In any case, the error doesn't seem to originate from raymob in your case either.

Therefore, I recommend reaching out to the Termux community for assistance, as I'm afraid I may not be of much help on this matter.
