### ISSUE TITLE
Renaming `application_id` in 5.0 fails

### ISSUE THREAD

**Issue by rpav** [Bigfoot71/raymob#13]
So on master / 5.0 with only the following change:

```
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true
android.enableJetifier=false
android.useAndroidX=false

# Project name in Android Studio
projectName=myapp

# Name of your project
app.name=myapp
app.native_library_name=myapp
app.application_id=com.example.myapp

# Screen orientation [ portrait | landscape ]
app.orientation=landscape

# Project version
app.version_name=1.0
app.version_code=1

# raymob features
features.internet=false
features.vibration=false
features.accelerometer=false
features.soft_keyboard=false
features.display.keep_on=true
features.display.immersive=true
features.display.into_cutout=true
``` 

This fails to build with:

```
  :
> Task :app:lintReportDebug
Wrote HTML report to file:///path/to/raymob/app/build/reports/lint-results-debug.html

> Task :app:lintDebug FAILED
Lint found 1 errors, 5 warnings. First failure:

/path/to/raymob/app/src/main/AndroidManifest.xml:27: Error: Class referenced in the manifest, com.example.myapp.NativeLoader, was not found in the project or the libraries [MissingClass]
            android:name=".NativeLoader"
                          ~~~~~~~~~~~~~

   Explanation for issues of type "MissingClass":
   If a class is referenced in the manifest or in a layout file, it must also
   exist in the project (or in one of the libraries included by the project.
   This check helps uncover typos in registration names, or attempts to rename
   or move classes without updating the XML references properly.

   https://developer.android.com/guide/topics/manifest/manifest-intro.html


The full lint text report is located at:
  /path/to/raymob/app/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintDebug'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or create a baseline to see only new errors.
  To create a baseline, run `gradlew updateLintBaseline` after adding the following to the module's build.gradle file:
  
  android {
      lint {
          baseline = file("lint-baseline.xml")
      }
  }
  
  For more details, see https://developer.android.com/studio/write/lint#snapshot

  Lint found 1 errors, 5 warnings. First failure:

  /path/to/raymob/app/src/main/AndroidManifest.xml:27: Error: Class referenced in the manifest, com.example.myapp.NativeLoader, was not found in the project or the libraries [MissingClass]
              android:name=".NativeLoader"
                            ~~~~~~~~~~~~~

     Explanation for issues of type "MissingClass":
     If a class is referenced in the manifest or in a layout file, it must also
     exist in the project (or in one of the libraries included by the project.
     This check helps uncover typos in registration names, or attempts to rename
     or move classes without updating the XML references properly.

     https://developer.android.com/guide/topics/manifest/manifest-intro.html


  The full lint text report is located at:
    /path/to/raymob/app/build/intermediates/lint_intermediate_text_report/debug/lint-results-debug.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 16s
103 actionable tasks: 103 executed
```

I saw #7 and checked out the referred commit and this builds as expected without error.

**Comment by Bigfoot71** [comment]
@rpav I've also just tried it on the master branch (https://github.com/Bigfoot71/raymob/commit/0041474d5390d68918be574db821968c98ab445b) and everything is working as expected on my end.

Here's the `gradle.properties` that I used:
```gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true
android.enableJetifier=false
android.useAndroidX=false

# Project name in Android Studio
projectName=myapp

# Name of your project
app.name=myapp
app.native_library_name=myapp
app.application_id=com.example.myapp

# Screen orientation [ portrait | landscape ]
app.orientation=landscape

# Project version
app.version_name=1.0
app.version_code=1

# raymob features
features.internet=false
features.vibration=false
features.accelerometer=false
features.soft_keyboard=false
features.display.keep_on=true
features.display.immersive=true
features.display.into_cutout=true
```

_Proof_ of build and installation:
<img src="https://github.com/Bigfoot71/raymob/assets/90587919/69129a62-3608-471c-bfe4-b029511b943f" width="360" height="300">
<img src="https://github.com/Bigfoot71/raymob/assets/90587919/81c1ca1a-ed43-4dba-9311-3b72c1c5fa04" width="360" height="475">

- **Have you properly synced your project after modifying your `gradle.properties`?**

- **Are you sure you haven't modified any instance of `com.raylib.raymob` or anything else outside of `gradle.properties`?**

- **Do you think you've made any other modifications elsewhere?**

I simply cloned the repository, modified the `gradle.properties`, synced the project, and built/launched the application on my device, and everything worked perfectly on the first try.

**Comment by rpav** [comment]
I think I didn't sync; let me try that.

**Comment by rpav** [comment]
Err is this an Android Studio specific thing?  (Sorry this is probably obvious stuff, but I haven't touched android dev in years.) 

I'm building from the shell, no Android Studio involved.  All indications seem to be `./gradlew build` will do the proper steps and build, but, I get the above error.

I have not modified any other files / changed "com.raylib.raymob", etc.

**Comment by Bigfoot71** [comment]
@rpav My apologies, I assumed you were using Android Studio.

Via your terminal, navigate to the root directory of your 'raymob' project and try one of these commands:
```shell
sh gradlew assembleRelease    # Built an release APK for all architectures (ARM/x86 32/64bit)
sh gradlew assembleDebug      # Built an debug APK for all architectures (ARM/x86 32/64bit)
```
_Note: These are intended for Linux, but you can do the same with gradlew.bat on Windows._

You should find the output APK in `your_project/app/build/outputs/apk`
Depending on your needs, you can do `sh gradlew tasks --all` to see all available options.

_Note: Remember that in this way the generated APKs will not be signed, you will have to do it manually._

**Comment by rpav** [comment]
Confirmed!  Thanks.  Last time I worked on Android stuff it was still mostly ant!

**Comment by Bigfoot71** [comment]
haha, glad it's working! Good luck with the rest of your projects!

**Comment by maiconpintoabreu** [comment]
Hi there, sorry to ping here on this old issue but how it works without renaming the java folders?

And if renaming it, the build-gradle breaks as we because it uses hard coded path like: https://github.com/Bigfoot71/raymob/blob/6ff85822872391f399c80771981d8ce25e0a4cfd/app/build.gradle#L96

Maybe we could reopen this issue or should I create another one?

**Comment by Bigfoot71** [comment]
@maiconpintoabreu You normally shouldn't change occurrences of `com.raylib.raymob` anywhere other than in `gradle.properties`, otherwise you may break the build system...

You can change the application ID (and other values/features) directly in `gradle.properties`:
https://github.com/Bigfoot71/raymob/blob/master/gradle.properties#L12

The build system then handles everything automatically. Sorry that this may not be documented, I’m planning to revisit raymob soon to clean it up and bring it up to date

**Comment by maiconpintoabreu** [comment]
Hi @Bigfoot71 , the problem for me is the namespace was not matching the folder structure, and it was failing to build only changing the application id. It worked when I changed the folder structure to match the application id.
I can add some screenshots later.

**Comment by Bigfoot71** [comment]
Well, normally you shouldn't have to modify all of that, you just need to change `gradle.properties`, and everything will be correct when you generate your APK/AAB

But if you want to redo everything custom for some reason, the best option would simply be to remove all of that renaming logic from `build.gradle` and handle the rest however you prefer

Edit: If you want to open another issue with more details, I'll take a look at it

**Comment by maiconpintoabreu** [comment]
So, I was using a old version of Java and it was the issue with the folder/namespace thing, working fine with java 21, thanks.
