### ISSUE TITLE
Vibration is not working

### ISSUE THREAD

**Issue by mfbulut** [Bigfoot71/raymob#15]
My device is Samsung A52 and I was unable to vibrate the device
I call Vibrate(1.0f) and nothing happens

I use latest androuid studio and NDK

**Comment by mfbulut** [comment]
my bad i did't know you have to enable it via

features.vibration=true

**Comment by Bigfoot71** [comment]
Yes, because it is necessary to include the permission in the AndroidManifest, which is:
```xml
<uses-permission android:name="android.permission.VIBRATE"/>
```

As with all the features supported by raymob that require permissions, it is indeed centralized in the gradle.properties for simplicity reasons.
