### ISSUE TITLE
Add `context.getCacheDir` in `raymob.h`

### ISSUE THREAD

**Issue by cattokomo** [Bigfoot71/raymob#16]
Adding `context.getCacheDir` in the header file would be nice.

**Comment by Bigfoot71** [comment]
@cattokomo Thanks for the suggestion, this is done in https://github.com/Bigfoot71/raymob/commit/33f42d40c286f0d5de6b8a6aa85c43089f1abed3

So now you have the `GetCacheDir(void)` function provided in `raymob.h`.
The function allocates memory on the heap for the returned string, **remember to free it!**
