### ISSUE TITLE
open file i GetCacheDir bad fopen mode "rt"

### ISSUE THREAD

**Issue by GreenSnakeLinux** [Bigfoot71/raymob#18]
Hello,

When I want to read a file in cache folder using GetCacheDir()
I need to use: fopen(fileName, "r");
because LoadFileText(fileName) use mode "rt"  and return "Failed to open text file"
Why use "rt" ? Strangely, files open in asset folder is working with LoadFileText and mode "rt" but not with "r"

**Comment by Bigfoot71** [comment]
Hi, my memory isn't very fresh on all this, but I know that raylib internally uses its "own version" of `fopen` ([see utils.c](https://github.com/raysan5/raylib/blob/master/src/utils.c#L452)) for Android.

This might be the reason why `LoadFileText` is unable to read from the directory provided by `GetCacheDir`. To be verified...

In any case, this issue would be more appropriate for raylib itself. I will integrate the changes made in the official repository afterward, if there is any.

**Comment by GreenSnakeLinux** [comment]
you're right it is not related to "rt" mode but with:
#define fopen(name, mode) android_fopen(name, mode)
I have created a pull request, to have a new read function, that does not read in Assets folder but everywhere including cache directory.

**Comment by Bigfoot71** [comment]
@GreenSnakeLinux I just reviewed your contribution, and aside from a few minor things to address, it looks great! Thank you again!

**Comment by Bigfoot71** [comment]
Completed with: https://github.com/Bigfoot71/raymob/pull/19 and https://github.com/Bigfoot71/raymob/commit/9ea2fe1f962d885839ad9c585d114c2d63d5bd7d

Thanks again @GreenSnakeLinux ! :)
