### ISSUE TITLE
How to compile to desktop

### ISSUE THREAD

**Issue by RugiSerl** [Bigfoot71/Raymob#2]
I have a question: is it possible to compile the project to desktop and if yes, how ?

**Comment by Bigfoot71** [comment]
No, you cannot directly compile the project for desktop.

However, you can use the same source code by building it with the appropriate compiler.
You can also use these directives in your code to achieve the desired behavior based on the platform:
```c
#if defined(PLATFORM_DESKTOP)
    // Specific code for desktop platform
#elif defined(PLATFORM_ANDROID)
    // Specific code for the Android platform
#else
    // Code executed by default if none of the previous conditions is satisfied
#endif
```

You can also launch your Android project on an emulator from your PC or directly on your device by enabling debugging. You can easily do this through Android Studio or using the `adb` commands.

**Comment by RugiSerl** [comment]
ok, thank you for the explanations. I'm still new at c/c++ and android development.
