### ISSUE TITLE
shaders cannot be used

### ISSUE THREAD

**Issue by ASGART1907** [Bigfoot71/raymob#23]
Hello. I transferred raymob to the raylib project I use on Windows, everything works fine, but I cannot use the shaders. I know the shader is loaded but I can't draw anything. Is there anything I should know about this?                   Thanks...

**Comment by Bigfoot71** [comment]
What logs do you get? You can get them in the "logcat" tab on Android Studio

**Comment by ASGART1907** [comment]
I don't use Android studio, I use adb. But I don't know how to use debug.

**Comment by Bigfoot71** [comment]
Ah, in this case, it will be a bit more tricky. When your device is connected to your PC, before launching your application, run the following command (I assume you're on Linux, but you can find the PowerShell equivalent if needed):

```shell
adb logcat | grep <your_package_name>  # e.g.: com.raymob.app
```

Then, launch the application. This should show all the logs for your app.

This process might be a bit cumbersome, so before diving into that, let's eliminate some common issues:
- Are your shaders located in the `app/src/main/assets` directory?
- Are you loading them correctly, for example, assuming they are in the `assets` folder:
  ```c
  Shader shader = LoadShader("my_shader.vs", "my_shader.fs");
  ```
- By default, with raymob, you’re using OpenGL ES 2. Do your shaders have the correct version directive? For example: `#version 100`
