### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by ruby-bang** [Bigfoot71/raymob#26]
I never code android before. just pure c.

if I change package name 

default: com.raylib.raymob
to : com.kamutu.bajing

it makes the app not detected as a game. can you help me?.

**Comment by Bigfoot71** [comment]
Do you mean that the application is no longer recognized as a game by Android once installed?  
To be honest, I don’t think I did anything in raymob to influence that, so if it worked before, it’s strange...  

I didn’t make any assumptions about the type of applications people might create with raymob. However, you’ve made me realize that it could be a good addition as a flag in the raymob properties file.

Anyway, did I understand correctly what you meant?

**Comment by ruby-bang** [comment]
yes that what I mean.

**Comment by Bigfoot71** [comment]
@ruby-bang You can now specify the category of your application using the `app.category` field in [gradle.properties](https://github.com/Bigfoot71/raymob/blob/master/gradle.properties#L15)
